### PR TITLE
Fix Gradle build failure

### PR DESCRIPTION
**Pull request by josmil1**
Requires upgrade to Android Studio 3.0

### CODE REVIEW

**Comment by HansKristian-ARM** [comment]
Requiring 3.0 is a bit much (lots of breakage in 3.0), can you try to update support for 2.3.3?

**Comment by josmil1** [comment]
Hi Hans-Kristian, what do you mean? All samples seemed to build and run fine

**Comment by HansKristian-ARM** [comment]
Does this also work out-of-the-box with a clean Android Studio 2.3.3 install? If it does, this is fine.

**Comment by josmil1** [comment]
Unfortunately Gradle 3.0.0 requires Android Studio 3.0. I tried installing Android Studio 2.2.3 but this commit does not work, worth investigating further?
The reason I updated Android Studio was to solve this issue: https://github.com/ARM-software/vulkan-sdk/issues/7

**Comment by HansKristian-ARM** [comment]
Gradle 2.3.3 should work on Android Studio 3.0 as well.

**Comment by josmil1** [comment]
Indeed, I checked that Gradle 2.3.3 works on Android Studio 3.0. However, would you like me to try some other version of Android Studio? It is incompatible with Android Studio 2.2.3 for example.

**Comment by HansKristian-ARM** [comment]
2.3.3 is good enough I think.

**Comment by JoseEmilio-ARM** [comment]
OK sorry, I am getting a bit confused between Android Studio version, Gradle version, and Gradle Plugin version.
I can confirm that the Gradle Plugin version 2.3.3 (and Gradle version 4.1) works with Android Studio versions 2.3.3 and 3.0.

**Comment by JoseEmilio-ARM** [comment]
Updated the Plugin version, anything else?

**Pull request merged**
